- hosts: all
  tasks:
    - name: Check if UTCoverage directory exists
      stat:
        path: "{{ zuul.project.src_dir }}/python3-k8sapp-harbor/k8sapp_harbor/UTCoverage"
      register: utcov_dir
    - name: Upload coverage reports
      synchronize:
        src: "{{ zuul.project.src_dir }}/python3-k8sapp-harbor/k8sapp_harbor/UTCoverage/"
        dest: "{{ zuul.executor.log_root }}/coverage/"
        mode: pull
      when: utcov_dir.stat.exists
      failed_when: false
    - name: Return coverage report URL
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: "Coverage Report"
                url: "coverage/htmlcov/index.html"
      when: utcov_dir.stat.exists
